linters:
  disable-all: true
  enable:
    - wrapcheck
    - wsl
    - gomoddirectives
    - gocritic
    - gosimple
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goconst
    - gofmt
    - gomnd
    - whitespace
linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/spf13/cobra.Command).MarkFlagFilename
