linters:
  disable-all: true
  enable:
    - wrapcheck
    - wsl
    - gomoddirectives
    - gocritic
    - gosimple
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goconst
    - gofmt
    - whitespace
linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/spf13/cobra.Command).MarkFlagFilename
  wrapcheck:
    ignoreSigs:
      - .WriteFile(
      - .Marshal(
      - k8s.io
      - command.SetCommandOptions(
      - fmt.Errorf(
