name: goreleaser

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write
  # issues: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: |
          git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          hooks: goreleaser
          allow-initial-development-versions: true
